=== SviatlanaYermalinskaya/JavaTestAutomation/MavenProject/messages.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="messages">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="message" maxOccurs="unbounded" minOccurs="1">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="to" type="xs:string"/>
                     <xs:element name="subject" type="xs:string"/>
                     <xs:element name="msgbody" type="xs:string"/>
                  </xs:sequence>
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== SviatlanaYermalinskaya/JavaTestAutomation/MavenProject/messages.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="messages.xsd">
    <message>      
      <to>esalana@tut.by</to>
      <subject>Test 1</subject>
      <msgbody>It's a test message!</msgbody>      
    </message>   
    <message>      
      <to>orimailrb@gmail.com, esalana@tut.by, lanalex@tut.by</to>
      <subject>Test 2</subject>
      <msgbody>Hello!</msgbody>      
    </message>  
</messages>
